# Generated by Django 3.2.7 on 2022-01-08 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='collection_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uName', models.CharField(max_length=500)),
                ('book_Name', models.CharField(max_length=100)),
                ('book_url', models.CharField(max_length=2000)),
                ('book_Price', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('book_Info', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
