# Generated by Django 3.2.7 on 2022-01-11 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_collection_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_table',
            name='ISBN',
            field=models.CharField(default=0, max_length=1000),
        ),
    ]
