# Generated by Django 3.2.7 on 2022-01-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_collection_table_isbn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection_table',
            name='ISBN',
        ),
    ]
