# Generated by Django 3.2.7 on 2022-01-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_collection_table_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection_table',
            name='lib',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
